components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks
        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.
 
        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 1
 
    default_task_processor: main-task-processor  # Task processor in which components start.
 
    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: 8000            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dns-client:
            fs-task-processor: fs-task-processor

        http-client:
            fs-task-processor: fs-task-processor
            user-agent: $server-name
            user-agent#fallback: 'userver-based-service 1.0' 

        keycloak-auth:
            keycloak_url: http://keycloak:8080
            realm: reports-realm
            client_id: reports-api
            client_secret: oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq
                    
        auth-check-middleware: {}
        cors-middleware: {}
        custom-middleware-pipeline-builder: {}

        handler-reports:
            path: /reports
            method: GET,OPTIONS
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: custom-middleware-pipeline-builder
                auth-check-middleware: 
                    allowed_roles:
                        - prothetic_user
                cors-middleware:
                    allow_credentials: true

                
